//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentExam.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentMaster()
        {
            this.StudentDetails = new HashSet<StudentDetail>();
        }
    
        public int StudentId { get; set; }
        public string Name { get; set; }
        public Nullable<int> ExamId { get; set; }
        public string ClassName { get; set; }
        public Nullable<int> RollNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentDetail> StudentDetails { get; set; }
        public virtual Exam Exam { get; set; }
    }
}
